{% set name = "mne-rsa" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: baa6955a80419427c13f4b5322b7cebce4427ad5aa5e9869c47a44d683728422

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base
    - mne-base
    - nibabel
    - scikit-learn

test:
  imports:
    - mne_rsa
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://users.aalto.fi/~vanvlm1/mne-rsa/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Representational Similarity Analysis on MEG and EEG data
  description: |
    This is a Python package for performing representational similarity
    analysis (RSA) using MNE-Python data structures. The RSA is computed using
    a “searchlight” approach.
  dev_url: https://github.com/wmvanvliet/mne-rsa

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - wmvanvliet
