{% set name = "mne-rsa" %}
{% set version = "0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8c2840d8f3210978fd35b05f8eca505d29591afe8a5dd5e3f8bc25e22a2d5b13

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - mne-base
    - nibabel
    - scikit-learn

test:
  imports:
    - mne_rsa
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://users.aalto.fi/~vanvlm1/mne-rsa/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Representational Similarity Analysis on MEG and EEG data
  description: |
    This is a Python package for performing representational similarity
    analysis (RSA) using MNE-Python data structures. The RSA is computed using
    a “searchlight” approach.
  dev_url: https://github.com/wmvanvliet/mne-rsa

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - wmvanvliet
